name: es_compression
description: Compression framework providing FFI implementations for Brotli, Lz4, Zstd (Zstandard) with ready-to-use prebuilt binaries for Win/Linux/Mac.
version: 0.9.9
homepage: https://www.instantiations.com
issue_tracker: https://github.com/instantiations/es_compression/issues
repository: https://github.com/instantiations/es_compression

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  escompress: es_compress

dependencies:
  args: ^1.6.0
  ffi: ^0.1.3

dev_dependencies:
  benchmark_harness: ^1.0.4
  collection: ^1.14.0
  effective_dart: ^1.2.4
  pedantic: ^1.8.0
  test: ^1.6.0
